### ISSUE TITLE
[BUG] No webhook / not running check group

### ISSUE THREAD

**Issue by paulijones** [tianhaoz95/check-group#544]
**Describe the bug**
check-group installed from the marketplace does not run on selected repos

**To Reproduce**

1. Go to github marketplace and install the app for a specific repo
2. follow setup doc / create `.github/checkgroup.yml`
3. Create PR with change that triggers workflows
4. no checkgroup check occurs

**Expected behavior**
I expected to see a Check Group check that passed once the specified checks in the `.github/checkgroup.yml` passed. Instead it isn't listed in the checks

**Screenshots**
![image](https://user-images.githubusercontent.com/30155889/130669640-a5e43e70-60ae-4b83-ac2b-171a69d15825.png)

**Additional context**
My suspicion is that there needs to be a webhook setup to call out to your service. I looked and didn't see one created either at the repo level or at the organization level.

Let me know if there is any other info i can provide or anything i can do to help! this project looks perfect for my use case and i'd love to get it up and running. Many thanks!

**Comment by tianhaoz95** [comment]
Hi @paulijones! Thanks for trying out the project :)

I took a look at the log and found that it's because heroku server is out of free hours... I guess since we are approaching the end of this month...

![Screenshot_20210824-115606_Chrome](https://user-images.githubusercontent.com/16887772/130674424-251c36aa-d6dc-4e1f-a567-11f8c3e2c997.jpg)

so there are a few near future solutions for this that I will implement after this busy week with my 9to5 job:

1. there is an ongoing migration from heroku to vercel as the service provider which should avoid this issue since vercel calculates usage by seconds whereas heroku will round anything under 30 minutes to 30 minutes (this will also improve response time since vercel doesn't have server warm up time)
2. Continue paid heroku for a few more weeks until the migration is done. It turns out that I cancelled the paid service before the migration is done. This should be fairly easy, but I want to check if it's urgent for people to keep the service up between now and the end of this month since I few users that I know was pretty busy with other stuff recently

**Comment by paulijones** [comment]
Thanks for the quick response! We aren't using it yet and were just looking to see if it would solve our problem, nothing that can't wait another week.

I'd be happy to help with the migration if you have steps laid out. I don't know vercel, but it wouldn't be the first (or last) time i migrated things away from heroku :laughing: 

If it does work for us, we would be looking to use this in our main path for one of our production products. I'm a little worried about pr's suddenly being blocked at the end of each month. Have you considered either a paid tier or a guide for self-hosting the docker image? i'd happily consider either if it works for us.

**Comment by tianhaoz95** [comment]
Thanks for helping out! The migration is pretty much just copying over a ton of credentials.

I just migrated it in #564. The migrated pipeline might bring up some issues since vercel is a pretty opinionated platform. Please bring it up in issue if anything seems off.

**Comment by tianhaoz95** [comment]
Yes, I am thinking about hosting a more reliable version like 98% uptime but have been debating what is the best way to pull it out.

There is a dockerized self-hosted solution available, but I don't really recommend it since the time it takes to configure/maintain the webhooks and credentials is too long, and it really defeats the purpose of providing an easy to use/understand automation.

For now, after migrating to Vercel, the monthly cap is gone, and we don't need to worry about traffic for a while until the active user count exceed 500 by estimation... My current plan is to monitor the usage, when it goes anywhere near 50% of the limit, I will separate out some sort of paid version which runs on high reliability AWS lambda.

**Comment by tianhaoz95** [comment]
Oh also, since the promotion season in my 9to5 job is about to finish, I will have significantly more time to work on this. If you have some timeline for your project or some feature wish list, you can add it here or email me so that I can take into consideration when I plan my time :)
