### ISSUE TITLE
[BUG] Support repositories where there are more than 30 check runs

### ISSUE THREAD

**Issue by jtbeach** [tianhaoz95/check-group#744]
**Describe the bug**
Currently the `getPostedChecks` function which works out which checks have successfully passed does not handle pagination in the Github API. The default Github API will only return the first 30 records. Specifically, this line: https://github.com/tianhaoz95/check-group/blob/master/src/core/index.ts#L141

**To Reproduce**

1. Create a Github Actions workflow with more than 30 jobs
2. Add required checks to the checkgroup config which would not be returned in the first 30 results
3. Observe that even when the Github Actions job has conclused and posted status, Check Group cannot detect that the job has concluded.

**Expected behavior**
getPostedChecks to handle pagination. I'm happy to raise a PR if we can get merged and deployed @tianhaoz95? I think the approach described here will work: https://michaelheap.com/octokit-pagination/

**Comment by tianhaoz95** [comment]
Thanks for pointing out the issue!

Definitely, all the things merged to master gets auto deployed. I usually review and merge PRs within a few days or at least finish by the first weekend if 9-5 job has crazy deadlines :)

It looks like the approach in the link can replace the current implementation without modifications in other places. If you want to take that from a user defined max value, you can check out the user config parser in https://github.com/tianhaoz95/check-group/tree/master/src/utils/user_config_parser.

Also, since not many project will like have checks that is more than 50, I think putting a hard coded number like 100 should solve the issue and if there is any request to customize we can deal with that later.

Or other implementation might work as well. Please feel free to pick the one that feel right to you :)

For testing, there are 2 ways:

1. Set up fake app and connect to a fake repository. This reflects the closes behavior but takes some time to set up.
2. Add a mocked integration test in https://github.com/tianhaoz95/check-group/tree/master/test. Unfortunately, all the functions that requires a nock connection is in the integration test instead of unit test like things in https://github.com/tianhaoz95/check-group/tree/master/src/utils

> p.s. I was planning on adding an one pager for how to develop locally for a while now, but was a bit lazy :)

**Comment by jtbeach** [comment]
Thank @tianhaoz95 -- I've raised a PR (#745). I didn't quite follow you comment on adding an integration test. I did try to run tests locally but I don't have access to the test repo I believe on Github

**Comment by tianhaoz95** [comment]
@all-contributors please add @jtbeach for code ideas
